#!/usr/bin/env bash
# Script that installs Nginx server and redirects
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /etc/nginx/html/index.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;'
service nginx start

