#!/usr/bin/env bash
# Server-01 login commands

# Setting up the SSH-agent
eval $("ssh-agent")

# Path to IdentityFile
ssh-add ~/.ssh/new_key_pair

# Username and IP Address 
ssh ubuntu@54.197.110.225
