#!/usr/bin/env bash
#Displays messages when read some signals
echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command"; rm -r /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -r /var/run/myscript.pid; exit' SIGQUIT
while :
do
    echo "To infinity and beyond"
    sleep 2
done
